pipeline {
    agent { label 'robot' }

    options {
        timestamps()
    }

    stages {
        stage('Install Dependencies') {
            steps {
                dir('openweather-api-automation') {
                    sh 'python3 -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run API Tests') {
            steps {
                dir('openweather-api-automation/developer_style_API_testing') {
                    withCredentials([string(credentialsId: 'openweather-api-key', variable: 'OpenWeather_API_KEY')]) {
                        sh 'python3 -m robot -i smoke -L TRACE -d results TestCases'
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'openweather-api-automation/developer_style_API_testing/results/*', allowEmptyArchive: true, fingerprint: true
        }
    }
}
