pipeline {
    agent { label 'agent-node' }

    options {
        timestamps()
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/akilamadhufin/API-Testing.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('Robot‑native API testing') {
                    sh 'python3 -m pip install -r requirements.txt'
                }
            }
        }

        stage('Run API Tests') {
            steps {
                dir('Robot‑native API testing') {
                    withCredentials([string(credentialsId: 'openweather-api-key', variable: 'OPENWEATHER_API_KEY')]) {
                        sh 'python3 -m robot -i smoke -L TRACE -d results TestCases'
                    }
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'Robot‑native API testing/results/*', allowEmptyArchive: true, fingerprint: true
        }
    }
}
